[tools]
java = "zulu-8.86.0.25"
jq = "latest"
# You may want to match the version we're currently building our Docker images
# from:
# https://github.com/mdg-private/platform-docker/blob/main/kafka/Dockerfile
kafka = "apache-2.8.2"
maven = "3.9.9"

[tasks.build]
# Oddly, Maven only sets the executable bit on the shell script when it adds it
# to its tarball.
run = "mvn install && chmod +x {{config_root}}/target/kafka-assigner-pkg/bin/kafka-assignment-generator.sh"

[env]

# Add the built kafka-assignment-generator.sh script and our scripts to PATH.
_.path = [
    "{{config_root}}/target/kafka-assigner-pkg/bin",
    "{{config_root}}/apollo-scripts",
]
